// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upipcvzcphqidobkhqyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwaXBjdnpjcGhxaWRvYmtocXljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2MTAyNjgsImV4cCI6MjA1NDE4NjI2OH0.Sl2XMQPI0cYqXCEaAu1HzC2rVmcC0wp9TIkRZN46ElQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);